### ISSUE TITLE
Consider not doing tight integration with other outputs, only cloudevents?

### ISSUE THREAD

**Issue by n3wscott** [nsmith5/rekor-sidekick#17]
Cool!!!

Lots more thoughts in https://falco.org/blog/falcosidekick-response-engine-part-3-knative/

I bet you get the same milage for your buck if you integrate "cloudnatively" rather than needing to do the integrations in this project.

Let me know if you want to chat about this.

**Comment by nsmith5** [comment]
@n3wscott Yes! lets absolutely chat! I learned about cloud events just this morning and would love to learn more

**Comment by nsmith5** [comment]
@n3wscott I've added some basic support for cloud events over in #20. Do you fancy giving it a review? Having looked at the cloud events ecosystem and landscape the vision is really awesome, but I don't want to limit this project to only working for folks that have adopted cloud events. I'm excited to support cloud event output, but want to have some other options that add value for folks that don't know about cloud events
